### ISSUE TITLE
BH stops working (freezes)

### ISSUE THREAD

**Issue by Endeavour79** [c00w/bitHopper#256]
http://pastebin.com/ffaJ19yw

Debug at Pastebin

**Comment by c00w** [comment]
Whee 2^8. And I think I fixed this a couple of minutes ago. IF it appears again tell me.

**Comment by simonk83** [comment]
Happening to me as well (still happening).  This time, when it "froze", I left it a bit and it sort of kicked back it, but seemed very slow and spotty.  Eventually I got the following errors in the console:

http://pastebin.com/rFFf3dXK

Seems connection related, but everything has been fine before the switch away from Twisted today.

**Comment by c00w** [comment]
I made one fix today. I think this is unrelated to that fix. What miner are you using?

**Comment by simonk83** [comment]
I'm using cgminer, with 4 gpu's.

**Comment by hawks5999** [comment]
also getting the Old Work and Database freezing errors. Guiminer, 11 miners

**Comment by sdogi** [comment]
I can confirm freezing on Ubuntu after about two hours or so. Unfortunately I wasn't running bitHopper through debugger. I got no errors.. just to had two writing to database messages in a row and although wet interface appeared it didn't list any pools. Only the top header.

Going to run it through debugger now and see what's up.

**Comment by sdogi** [comment]
What OS are you guys running? Would be easier to debug on my Windows development machine but not sure if this bug affects Windows too.

**Comment by simonk83** [comment]
I'm on Windows 7 x64 ;)

**Comment by c00w** [comment]
Wait the database is freezing? Because I'm patching it with eventlet. I can undo that.

**Comment by simonk83** [comment]
That's the point where it screws up c00w:

writing to database

If you leave it long enough it can come good again, but not always.

**Comment by c00w** [comment]
I undid the eventlet patching See if this works better.

**Comment by simonk83** [comment]
Still occurs unfortunately :(

**Comment by sdogi** [comment]
Yeah it is still happening. Next time I should be able to catch it though.

**Comment by c00w** [comment]
I pushed another patch to restart the wsgi server. We will see if it helps. I don't see why the wsgi server is running out of connections. I can drop it down to http/1.0 mode though.

**Comment by sdogi** [comment]
I'm about to go to bed but I see c00w that you have removed most of the semaphores and replaced them with RLocks probably to avoid deadlocking. Anyway I see that there is one semaphore still left:

lp.py:                self.polled[server] = threading.Semaphore()

So I'm wondering in here if LP receiving might not block all the threads and this is why it grinds to halt? Could you go over the logic in there and see if I'm onto something. Actually now that I check I see you are using non-blocking acquire with these server semaphores. 

I'm also seeing these messages:
http://pastebin.com/4rv0axg1

Also in lp.py

inside def receive(self, body, server):

Isn't there a bug with self.errors[server] logic. It seems that self.errors[server] never seems to be reset anywhere? So if any pool should receive 3 LP errors over time it would never pull LP anymore?

Couldn't this maybe affect the semaphore? Although now that I see that it is non-blocking I don't quite see the reason for it at all. With current self.error[server] logic I would imagine there would be awfully lot of release() 'es without any .acquires() at some point.

**Comment by sdogi** [comment]
Ok it happened again!

[04:12:05] LP Call http://ozco.in:8332/LP
[04:12:20] writing to database
[04:13:20] writing to database

So it could be because of LP handling after all.. trying to pause and debug

**Comment by Endeavour79** [comment]
Still freezing with the same issue.. Also in the latest build the same situation as in sdogis post above exists.

**Comment by Endeavour79** [comment]
Still freezing with the same issue.. Also in the latest build the same situation as in sdogi's post above exists.

**Comment by sdogi** [comment]
I'm still looking.. figured out why it is not possible to exit bithopper anymore without killing it. I think lot of people may lump this bug together with not being able to kill bithopper anymore. Anyway patch is available in my pull request / fork queue.

**Comment by sdogi** [comment]
OK I got full trace of this happening. It appears the blocking seems to be in work.py inside get() function that uses httplib2.Http()

And from what it appears it is SSL library related blocking. There are tons of this in the trace:

ssl:135:         try:
ssl:136:             return self._sslobj.read(len)
eventlet.green.ssl:156:             return read
socket:398:                     if not data:
socket:400:                     buffers.append(data)
socket:396:                 while data != "\n":
socket:397:                     data = recv(1)
eventlet.green.ssl:150:         if self._sslobj:
eventlet.green.ssl:151:             if flags != 0:
eventlet.green.ssl:155:             read = self.read(buflen)
eventlet.green.ssl:101:         return self._call_trampolining(
eventlet.green.ssl:102:             super(GreenSSLSocket, self).read, len)
eventlet.green.ssl:72:         if self.act_non_blocking:
eventlet.green.ssl:75:             while True:
eventlet.green.ssl:76:                 try:
eventlet.green.ssl:77:                     return func(_a, *_kw)

The loop starts with:
work:55:             try:
work:56:                 content = http.request( url, 'GET', headers=header)[1] # Returns response dict and content str

I see you use specific version of httplib2. I wonder if this could be causing it or how about using urllib2 instead?

Full log file: https://raw.github.com/sdogi/bitHopper/logs/tracelog.txt

You can start following trace when you search for:
2 DBWRITE CALLS FOUND IN A ROW 2

And it sends with:
2 DBWRITE CALLS FOUND IN A ROW 3

**Comment by c00w** [comment]
Hmmm. The reason we use httplib2 is it allows us to specify get versus post since we send bodies on both of them. I did add a backdoor so we can figure out what is going on.

**Comment by c00w** [comment]
Since it looks like httplib is what is lagging out I added back timeouts which should help.

**Comment by c00w** [comment]
It looks like this has stopped happening after I solved the race condition. I'm closing the issue.
