### ISSUE TITLE
TCP/IP connections not cleaned up - lots of CLOSE_WAIT

### ISSUE THREAD

**Issue by bitcoindaddy** [c00w/bitHopper#259]
Running with the latest build (eventlet), bitHopper eventually fails due to a lack of file handles for Socket connections.   Doing a "netstat -tunp" shows lots of connections in a "CLOSE_WAIT" state.

**Comment by bitcoindaddy** [comment]
socket.error: [Errno 24] Too many open files

**Comment by sdogi** [comment]
Could you list pools you are currently using and with what settings are you running?

**Comment by bitcoindaddy** [comment]
python bitHopper.py --scheduler OldDefaultScheduler --p2pLP

ozco @3937MHash
   Disabled    Info    Mine Please Donate to c00w:1HEmzeuVEKxBQkEenysV1yM8oAddQ4o2TX 
Show Disabled Pools

Admin Tools:  
Server  Shares  Role    User Shares
Rejects Speed   Duration    Payout  Efficiency  Penalty Slice   Round Shares
Bitcoin.cz  631724
 34.98%          mine_slush 3599 / 41
 1.14%  1811.6  0h:25m  0.41063638
Exp: 0.09965660 412.1%  1.00    -  
BTCGuild.com    10948705
606.34%          mine_deepbit   13 / 0
 0.00%  2020.0      0.00000000
Exp: 0.00035997 0.0%    1.00    -  
DeepBit.com 1257381
 69.63%          mine_deepbit   25296 / 113
 0.45%  5619.0      1.17688575
Exp: 0.70044826 168.0%  1.00    -  
BitClockers.com 1959490
108.52%          mine   7597 / 83
 1.09%  202.1       0.13497374
Exp: 0.21036154 64.2%   1.00    -  
BitcoinMonkey.com   4256096
235.70%          mine   0 / 0
 0.00%  3.5     0.00000000
Exp: 0.00000000 -   1.00    -  
Bitcoins.lc 963652
 53.37%          mine_deepbit   5328 / 20
 0.38%  437.3       0.58382111
Exp: 0.14753274 395.7%  1.00    -  
BitMinersUnion.org  1956629
108.36%          info   0 / 0
 0.00%          0.00000000
Exp: 0.00000000 -   1.00    -  
BTCServ.net 1422286
 78.77%          mine   0 / 0
 0.00%          0.00000000
Exp: 0.00000000 -   2.00    -  
BitHasher.com   2225117
123.23%          mine   0 / 0
 0.00%          0.00000000
Exp: 0.00000000 -   1.00    -  
MtRed.com   2226497
123.30%          mine   11451 / 53
 0.46%  143.8       0.70899802
Exp: 0.31707910 223.6%  1.00    -  
PolMine.pl  6675792
369.71%          mine_deepbit   0 / 0
 0.00%  155.8   *2d:2h:2m   0.00000000
Exp: 0.00000000 -   1.00    -  
abcpool.co  1805700
100.00%          info   0 / 0
 0.00%          0.00000000
Exp: 0.00000000 -   1.00    -  
Bloodys.com 2106738
116.67%          mine   0 / 0
 0.00%          0.00000000
Exp: 0.00000000 -   1.00    -  
SwePool.net 4597775
254.63%          mine   0 / 0
 0.00%  5.2 22d:20h:21m 0.00000000
Exp: 0.00000000 -   1.00    -  
OzCo.in 185098
 10.25%          mine   6229 / 1
 0.02%  268.8   0h:52m  0.57387724
Exp: 0.17248151 332.7%  1.00    -  
BitcoinPool.com 4593640
254.40%          info   0 / 0
 0.00%  187.6   *1d:3h:10m  0.00000000
Exp: 0.00000000 -   1.00    -  
NoFeeMining.com 1451599
 80.39%          mine   13 / 0
 0.00%  3.6     0.00000000
Exp: 0.00035997 0.0%    1.00    -  
Eligius.st  7443811
412.24%          backup 15947 / 47
 0.29%          0.00000000
Exp: 0.44157370 0.0%    1.00    -  
TripleMining.com    7128603
394.78%          mine   140 / 0
 0.00%          0.00000000
Exp: 0.00387661 0.0%    1.00    -  
BTCWorld.de N/A          api_disable    3605 / 54
 1.50%          0.00000000
Exp: 0.09982274 0.0%    1.00    -  
ArsBitcoin.com  505054
 27.97%          info   0 / 0
 0.00%          0.00000000
Exp: 0.00000000 -   1.00    -  
DigBTC.net  1698843
 94.08%          mine   0 / 0
 0.00%          0.00000000
Exp: 0.00000000 -   1.00    -

**Comment by bitcoindaddy** [comment]
I'm back on the pre-eventlet version, but the list above is essentially the same. I can't afford to use the new one until it becomes more stable.

**Comment by c00w** [comment]
It may be fixed with the latest version. the WSGI server wasn't closing sockets on exceptions. Can you confirm the error still appears as of the changes about an hour ago?

**Comment by bitcoindaddy** [comment]
No, it's not fixed yet, even after your change: 

16:58:19] writing to database
[16:59:19] writing to database
[17:00:19] writing to database
[17:01:19] writing to database
[17:02:19] writing to database
[17:03:19] writing to database
Traceback (most recent call last):
  File "bitHopper.py", line 217, in <module>
    main()
  File "bitHopper.py", line 213, in main
    wsgi.server(eventlet.listen((options.ip,options.port)),bithopper_instance.website.handle_start, log=log)
  File "/home/user/Downloads/bitHopper-c00w-20110821/eventlet/wsgi.py", line 596, in server
    client_socket = sock.accept()
  File "/home/user/Downloads/bitHopper-c00w-20110821/eventlet/greenio.py", line 154, in accept
    res = socket_accept(fd)
  File "/home/user/Downloads/bitHopper-c00w-20110821/eventlet/greenio.py", line 52, in socket_accept
    return descriptor.accept()
  File "/usr/lib/python2.6/socket.py", line 197, in accept
    sock, addr = self._sock.accept()
socket.error: [Errno 24] Too many open files

**Comment by c00w** [comment]
That is part of issue #256 which probably stems from this issue.

**Comment by c00w** [comment]
This is solved in the latest version. I am closing the issue. It was unrelated to #256 though since that actually stemmed from a race condition causing a deadlock.

**Comment by itstooez** [comment]
I'm starting to see this issue...I'm noticing that when it starts spamming in the logfile.txt, getworks and submissions still occur but sometimes the website goes down.  Roughly 10 G hash/s running through the ubuntu box.

Exception in wsgi server loop, restarting wsgi in 60 seconds
[Errno 24] Too many open files

When I run ss -s I notice TCP       ~1024 which is the limit of open files allowed per ulimit -a.

Using ss -a shows that there is a ton of ESTABLISHED connections to my miner...I would assume that bitHopper would only need a few connections to the miner...not sure why it's creating a vast amount of new ones to reach 1024.

I usually have to restart bitHopper, this orphans all the connections and then stops the wsgi error.

**Comment by c00w** [comment]
What miner are you using?

**Comment by itstooez** [comment]
GUIminer 20110824
phoenix 1.6.2

**Comment by c00w** [comment]
Um, phoenix leaks sockets since it doesn't support http1.1. You can either increase your socket size or see if you can force phoenix to support http1.1.

**Comment by itstooez** [comment]
Hmmm alright...leaking them as established and creating more...that's scary.  I'll see what I can do about switching to a different miner or trying phoenix 1.7.0 to see if the problem is corrected.  Any suggestions on how to increase my socket size ?

**Comment by c00w** [comment]
http://linux-yogi.blogspot.com/2010/04/increase-socketfile-open-limit-in-linux.html

echo "fs.file-max = 10000" >> /etc/sysctl.conf
sysctl -p

**Comment by itstooez** [comment]
Sweet, I had already changed the ulimit in /etc/security/limits.conf but neglected /etc/sysctl.conf

I'll make those changes, thanks c00w
