### ISSUE TITLE
BUG: Strage error and behaviour

### ISSUE THREAD

**Issue by paraipan** [c00w/bitHopper#448]
I get some errors in console li this...

[23:43:12] Setting Block Owner slush:00000000000004578ddfdb1dc83c6f9fbb1f44e62980e05c06ffa3835233ed1e
[23:43:13] slush api error:tuple indices must be integers, not str
...........................
[00:32:24] Setting Block Owner bcpool:00000000000000c2c6207362ee1703e48d90bc1b390a8d1ffe8acfff891e22e8
[00:32:25] bcpool api error:tuple indices must be integers, not str
..........................
[00:34:55] Setting Block Owner mtred:00000000000000c2c6207362ee1703e48d90bc1b390a8d1ffe8acfff891e22e8
[00:34:56] mtred api error:tuple indices must be integers, not str

and after that the new reassigned owner doesn't update round shares at all for long time. In the end it works again if that pool doesn't find any blocks.

**Comment by itstooez** [comment]
This was caused via https://github.com/c00w/bitHopper/commit/1579bc38068883becea8a6f0818e7f9043541bb5

Deepbit is on mine_lp, block gets heard by them -> db shares go to 0, LP sent to miners -> api updates for slush, block is reassigned to slush -> tuple indices error occur and api doesnt change

The goal is to have a 2nd LP callback sent to the miner, so that we don't miss short slush rounds (like the 49 second one earlier today) and others =]

**Comment by sdogi** [comment]
Guess this might be related:

[19:49:57] RPC request [] submitted to arsbitcoin
[19:50:00] DEBUG: received lp from: donation
[19:50:00] New Block: 000000000000085db6f81c31d0e1c740fa233747c173c2fec155e07d3db9568c
[19:50:00] Block Owner donation
[19:50:00] DEBUG: EXACT donation: 1318265400.06
[19:50:00] Setting Block Owner donation:000000000000085db6f81c31d0e1c740fa233747c173c2fec155e07d3db9568c
[19:50:00] DEBUG: Error in Long Poll donation{"id":1,"error":null,"result":{"midstate":"147421f39a1eac02676b4386c7e646cef01536ab6a92076ce79bfe6b35efc588","target":"ffffffffffffffffffffffffffffffffffffffffffffffffffffffff00000000","data":"000000013db9568cc155e07dc173c2fefa233747d0e1c740b6f81c310000085d00000000326b0ac35bbf7f7338970bcf507e78a406b2461270e58da8d2a453c84af935a34e931fff1a09ee5d00000000000000800000000000000000000000000000000000000000000000000000000000000000000000000000000080020000","hash1":"00000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000010000"}}
Traceback (most recent call last):
  File "/home/allan/bithopper-git/lp.py", line 188, in receive
    self.set_owner(server,block)
  File "/home/allan/bithopper-git/lp.py", line 95, in set_owner
    self.bitHopper.lp_callback.new_block(work, server)
  File "/home/allan/bithopper-git/lp_callback.py", line 26, in new_block
    merkle_root = work['data'][72:136]
TypeError: tuple indices must be integers, not str
[19:50:00] Long Poll Call http://su.mining.eligius.st:8337/LP
[19:50:02] RPC request [] submitted to arsbitcoin

Might look into this later

**Comment by c00w** [comment]
It looks like we are calling back with the wrong value....

**Comment by c00w** [comment]
I think I found it. Pushing a fix.

**Comment by paraipan** [comment]
yeah, got it :)
testing in a few moments

**Comment by itstooez** [comment]
http://pastebin.com/yq7rzeCH & http://pastebin.com/FtJHEhRk

When the block gets reassigned and the new owner isn't 'server'...it should only start mining at the new owner pool, if it's a valid mine role, right ?  Dont want LP callbacks sent for info/backup pools :) Looks like it's sending the getworks from my info pool.  Its not forcing the miner to gather new work

http://pastebin.com/65LzTV7t

Also, looks like the same block got reassigned 3 times ?

**Comment by c00w** [comment]
I was pulling works for the LP from the wrong server. Its fixed now.

**Comment by itstooez** [comment]
http://pastebin.com/8ygKUDqu

It's still not fixed.  LP went to deepbit, then re-assigned to Ars after their stats went to 0...shortly after, a share was submitted to Ars.  Ars is on backup.

What happens in lines 85-90, should be similar to what we are trying to do here I think...
