### ISSUE TITLE
Errors in stats in latest commit (4ac1c0ebf4b1e4724626)

### ISSUE THREAD

**Issue by macboy80** [c00w/bitHopper#45]
I get the following error when running bitHopper latest version. This is on win7 x64. Much earlier versions work well for me as well as the latest ryouiki. Please help...

Console Error (Program continues to run)

[10:53:30] Updating Difficulty
[10:53:31] 1690906.2047244
[10:53:31] Checking Database
[10:53:33] Database Setup
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "E:\BitHopper\c00w-bitHopper-4ac1c0e\bitHopper.py", line 425, in <module>
    main()
  File "E:\BitHopper\c00w-bitHopper-4ac1c0e\bitHopper.py", line 420, in main
    stats_call.start(117_4)
  File "C:\Python27\lib\site-packages\twisted\internet\task.py", line 163, in start
    self()
  File "C:\Python27\lib\site-packages\twisted\internet\task.py", line 194, in **call**
    d = defer.maybeDeferred(self.f, *self.a, *_self.kw)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 133, in maybeDeferred
    result = f(_args, *_kw)
  File "E:\BitHopper\c00w-bitHopper-4ac1c0e\stats.py", line 106, in update_api_stats
    d = work.get(self.bitHopper.json_agent,info['user_api_address'])
exceptions.NameError: global name 'work' is not defined
[10:53:34] poolmunity: 633,723
[10:53:34] Server change to poolmunity, telling client with LP

When I load the localhost:8337/stats this comes across the console

Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\protocols\basic.py", line 564, in dataReceived
    why = self.lineReceived(line)
  File "C:\Python27\lib\site-packages\twisted\web\http.py", line 1551, in lineReceived
    self.allContentReceived()
  File "C:\Python27\lib\site-packages\twisted\web\http.py", line 1619, in allContentReceived
    req.requestReceived(command, path, version)
  File "C:\Python27\lib\site-packages\twisted\web\http.py", line 773, in requestReceived
    self.process()
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\web\server.py", line 127, in process
    self.render(resrc)
  File "C:\Python27\lib\site-packages\twisted\web\server.py", line 147, in render
    body = resrc.render(self)
  File "C:\Python27\lib\site-packages\twisted\web\resource.py", line 216, in render
    return m(request)
  File "E:\BitHopper\c00w-bitHopper-4ac1c0e\bitHopper.py", line 322, in render_GET
    index = os.path.join(os.path.dirname(os.path.abspath(**file**)), 'index.html')
exceptions.NameError: global name '**file**' is not defined
[11:01:08] triple: 3,778,195
[11:01:09] btcmonkey: 2,344,912

Stats Page looks like this

web.Server Traceback (most recent call last):

<type 'exceptions.NameError'>: global name '**file**' is not defined
C:\Python27\lib\site-packages\twisted\web\server.py, line 127 in process
125    try:
126      resrc = self.site.getResourceFor(self)
127      self.render(resrc)
128    except:
Self
site  
twisted.web.server.Site instance @ 0x183c4e0 <twisted.web.server.Site instance at 0x0183C4E0>
Locals
resrc  
**main**.dynamicSite instance @ 0x18eed28 <**main**.dynamicSite instance at 0x018EED28>
self  
twisted.web.server.Request instance @ 0x18eead0 <GET /stats HTTP/1.1>
C:\Python27\lib\site-packages\twisted\web\server.py, line 147 in render
145    """
146    try:
147      body = resrc.render(self)
148    except UnsupportedMethod, e:
Locals
resrc  
**main**.dynamicSite instance @ 0x18eed28 <**main**.dynamicSite instance at 0x018EED28>
self  
twisted.web.server.Request instance @ 0x18eead0 <GET /stats HTTP/1.1>
Globals
UnsupportedMethod   <class 'twisted.web.error.UnsupportedMethod'>
C:\Python27\lib\site-packages\twisted\web\resource.py, line 216 in render
214               _computeAllowedMethods(self))
215      raise UnsupportedMethod(allowedMethods)
216    return m(request)
217
Locals
m   <bound method dynamicSite.render_GET of <__main__.dynamicSite instance at 0x018EED28>>
self  
**main**.dynamicSite instance @ 0x18eed28 <**main**.dynamicSite instance at 0x018EED28>
request 
twisted.web.server.Request instance @ 0x18eead0 <GET /stats HTTP/1.1>
Globals
_computeAllowedMethods  
function _computeAllowedMethods in file C:\Python27\lib\site-packages\twisted\web\resource.py at line 230
E:\BitHopper\c00w-bitHopper-4ac1c0e\bitHopper.py, line 322 in render_GET
320  isleaF = True
321  def render_GET(self,request):
322    index = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'index.html')
323    file = open(index, 'r')
Locals
self  
**main**.dynamicSite instance @ 0x18eed28 <**main**.dynamicSite instance at 0x018EED28>
request 
twisted.web.server.Request instance @ 0x18eead0 <GET /stats HTTP/1.1>
Globals
os  <module 'os' from 'C:\Python27\lib\os.pyc'>

<type 'exceptions.NameError'>: global name '**file**' is not defined

**Comment by Clipseza** [comment]
did you uncomment some pools in the pool.cfg after having them loaded into the database a previous session?

You can resolve this by clearing your database, or c00w could probably make changes that wont require database listed pools to be enabled by default.

**Comment by macboy80** [comment]
This issue is on a fresh install. Pool.cfg updated to mine a few disabled pools, but no extra disabled or redacted pools. I deleted all of the stats or db files to no avail, so I don't think that is the issue.

**Comment by c00w** [comment]
Um huh. That line should be index = os.path.join(os.path.dirname(os.path.abspath(**file**)), 'index.html')
not index = os.path.join(os.path.dirname(os.path.abspath(file)), 'index.html')

Reupdate? You might have somehow pulled at exactly the wrong moment. I'm looking into it.

**Comment by c00w** [comment]
Oh it is double underscore file double underscore.
Stupid github markup.

**Comment by c00w** [comment]
How are you running it? That could have an effect.

**Comment by macboy80** [comment]
This is where both my issues may be solved. I am opening bithopper.py in the python gui. Then clicking run from the menu at the top of the window.

**Comment by c00w** [comment]
Shoot. That runs it as an improrted module. let me look up a better way to do the code so that works.

**Comment by macboy80** [comment]
I'm also open to changing my ways... If you have a suggestion on how to do it normally. That may be what's causing my issue #46 as well. Also, I'm not sure when your code changed, but ryouiki still works, both stats and database not locking.

**Comment by c00w** [comment]
And there appears to be no better way. Um open it with the python.exe instead of doing it that way? I'll modify the code so you rmethod works.

**Comment by c00w** [comment]
Your method should work now with the latest version.

**Comment by macboy80** [comment]
Created a shortcut "D:\BitHopper\Python27\python.exe D:\BitHopper\c00w-bitHopper-4ac1c0e\bitHopper.py" Still getting the same error. That definitely fixes the database locking issue, though. I'll be looking for your fix. Thanks.

!!!EDIT: This is in regards to old version. Checking the new version now...

**Comment by macboy80** [comment]
Unfortunately, that didn't work for me. Both the command line "D:\BitHopper\Python27\python.exe D:\BitHopper\c00w-bitHopper-3628bd6\bitHopper.py" and the idle gui throw the same error as follows. Should I try to put bH files in python directory?

Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "D:\BitHopper\c00w-bitHopper-3628bd6\bitHopper.py", line 428, in <module>
    main()
  File "D:\BitHopper\c00w-bitHopper-3628bd6\bitHopper.py", line 423, in main
    stats_call.start(117_4)
  File "D:\BitHopper\Python27\lib\site-packages\twisted\internet\task.py", line 163, in start
    self()
  File "D:\BitHopper\Python27\lib\site-packages\twisted\internet\task.py", line 194, in **call**
    d = defer.maybeDeferred(self.f, *self.a, *_self.kw)
--- <exception caught here> ---
  File "D:\BitHopper\Python27\lib\site-packages\twisted\internet\defer.py", line 133, in maybeDeferred
    result = f(_args, *_kw)
  File "D:\BitHopper\c00w-bitHopper-3628bd6\stats.py", line 106, in update_api_stats
    d = work.get(self.bitHopper.json_agent,info['user_api_address'])
exceptions.NameError: global name 'work' is not defined

**Comment by c00w** [comment]
Should be fixed now.

**Comment by macboy80** [comment]
I will try, but I think I have found the error. I first started with your pool.cfg.default and added one pool at a time. Then I enabled one pool at a time. When I got to set bitclockers as mine, I got the error. Set to disable there is no error. I hate that I made you work for such an dumb mistake, but the problem is definitly in the pool.cfg for bitclockers. My code that throws the error:

[bitclockers]
name: bitclockers.com
mine_address: pool.bitclockers.com:8332 
user: macboy80
pass: xxxx
api_address:https://bitclockers.com/api 
api_method:json
api_key:roundshares
role:mine
user_api_address:https://bitclockers.com/api/%(bitclockers_user_apikey)s
bitclockers_user_apikey:677716f7b1d5c379643cb1e82f2b485e

Praise and donation coming your way.

**Comment by macboy80** [comment]
Tested newest commit with above "mine" for bitclockers. No luck. However, original issue is solved all the way back to commit (4ac1c0ebf4b1e4724626) if just disable bitclockers. The problem is in the above text. c00w you are awesome.

**Comment by c00w** [comment]
That code should work. I had to fix a bug in stats.

**Comment by macboy80** [comment]
With bitclockers enabled and latest commit (fe5860fa4c6c0e959c81), I still get error as follows. With disabled, everything looks good.

Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "D:\BitHopper\c00w-bitHopper-fe5860f\bitHopper.py", line 448, in <module>
    main()
  File "D:\BitHopper\c00w-bitHopper-fe5860f\bitHopper.py", line 443, in main
    stats_call.start(117_4)
  File "D:\BitHopper\Python27\lib\site-packages\twisted\internet\task.py", line 163, in start
    self()
  File "D:\BitHopper\Python27\lib\site-packages\twisted\internet\task.py", line 194, in **call**
    d = defer.maybeDeferred(self.f, *self.a, *_self.kw)
--- <exception caught here> ---
  File "D:\BitHopper\Python27\lib\site-packages\twisted\internet\defer.py", line 133, in maybeDeferred
    result = f(_args, *_kw)
  File "D:\BitHopper\c00w-bitHopper-fe5860f\stats.py", line 108, in update_api_stats
    d.addCallback(selectsharesResponse, (server))
exceptions.NameError: global name 'selectsharesResponse' is not defined

**Comment by c00w** [comment]
Can you try with the latest version? I fixed that bug as well.

**Comment by macboy80** [comment]
Same with this one (bd...). Enable bitclockers causes the following

Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "D:\BitHopper\c00w-bitHopper-bd59733\bitHopper.py", line 448, in <module>
    main()
  File "D:\BitHopper\c00w-bitHopper-bd59733\bitHopper.py", line 443, in main
    stats_call.start(117_4)
  File "D:\BitHopper\Python27\lib\site-packages\twisted\internet\task.py", line 163, in start
    self()
  File "D:\BitHopper\Python27\lib\site-packages\twisted\internet\task.py", line 194, in **call**
    d = defer.maybeDeferred(self.f, *self.a, *_self.kw)
--- <exception caught here> ---
  File "D:\BitHopper\Python27\lib\site-packages\twisted\internet\defer.py", line 133, in maybeDeferred
    result = f(_args, *_kw)
  File "D:\BitHopper\c00w-bitHopper-bd59733\stats.py", line 108, in update_api_stats
    d.addCallback(selfselectsharesResponse, (server))
exceptions.NameError: global name 'selfselectsharesResponse' is not defined

**Comment by c00w** [comment]
I am a retard and dropped a period. Try now?

**Comment by macboy80** [comment]
Presto! No big error, but it does throw an error in user api for bitclockers as follows. Could it be the https: instead of the http: it says on the site.

[00:29:01] Updating Difficulty
[00:29:01] 1690906.2047244
[00:29:01] Updating NameCoin Difficulty
[00:29:01] 94037.96
[00:29:01] Checking Database
[00:29:01] Database Setup
[00:29:03] mtred: 583,446
[00:29:03] Server change to mtred, telling client with LP
[00:29:03] bcpool: 1,616,340
[00:29:03] btcmonkey: 2,390,695
[00:29:03] triple: 4,538,568
[00:29:03] nofeemining: 1,188,869
[00:29:03] bitclockers: 428,758
[00:29:03] Server change to bitclockers, telling client with LP
[00:29:03] Error in user api for bitclockers
[00:29:03] rfc: 914,073
[00:29:04] ozco: 1,505,431
[00:29:05] bclc: 1,075,731
[00:29:06] btcworld: 572,446
[00:29:06] polmine: 2,086,650

**Comment by macboy80** [comment]
It's not the https: I tried http: with no luck.

EDIT: Looks like the error only shows up one time at the beginning of a run.

I'm good. Looks like you have solved all of my issues. If you need any Windows debugging help, feel free to PM me. I owe you one and would love to help.

**Comment by c00w** [comment]
Latest version should be fully debugged. On a different note bitclockers shouldn't be hopped. I don't remember if it was delayed stats or a changed algorithm but we dropped it for a reason.

**Comment by macboy80** [comment]
Everything is perfect! I've made some money on bitclockers with ryouiki fork, a little laggy, but I haven't seen anything bad yet. I think I'll ask the forum. Thanks again.
