### ISSUE TITLE
Workers Config Broken in Firefox and IE

### ISSUE THREAD

**Issue by TimLinton** [c00w/bitHopper#616]
I am presented with the error 
"Please confire some pools!
Go to localhost:8337/worker"

I try this but when I hit the plus sign, my worker ID / pass are NOT put into my user.cfg file. I can't find them saved anywhere really.. Nothing happens when I add workers.
I have a user.cfg file from previous bithopper builds that I would like to use, but when I try to use it, I am presented with the same error in the console.

I'd like to just use my custom made user.cfg file and run the server like before..

Thanks for the help

**Comment by c00w** [comment]
Users and passwords are now stored in workers.cfg and you can have more than 1 user per pool. Are the workers not showing up in that config file?

**Comment by TimLinton** [comment]
I don't seem to have a workers.cfg file ?

**Comment by c00w** [comment]
... Well thats a bug.

**Comment by c00w** [comment]
Can you run in debug mode and show me any tracebacks?

**Comment by TimLinton** [comment]
http://pastebin.com/u1EGxau5

I copied what I could.

**Comment by TimLinton** [comment]
http://pastebin.com/pmQqEdqh

**Comment by c00w** [comment]
Okay, I updated the README. Can you install gevent version 1.0b1? The link is in the readme and it should fix your problem. I can't reproduce it on my end in linux but it looks like an IPV6 compatibility bug.

**Comment by simonk83** [comment]
I'm actually having the same problem...  can't add any workers on the webpage and I have no workers.cfg

I had gevent 13 installed but I just installed 1.0b1 and it hasn't helped unfortunately :(

**Comment by TimLinton** [comment]
I did the update and sorry, i still dont see a worker.conf. Can you include the file in the release download? Then I can just add them by hand or with the utility.

**Comment by TimLinton** [comment]
http://pastebin.com/VC1Q20Fa

**Comment by TimLinton** [comment]
I run windows 7 32bit, and I get that error, and I just tried on my PC with windows 7 64bit, and still no go. Sorry but I just dont know.
Git is installed with the command prompt option selected.. I even did the "install.py" app, and still nothing. i don't know what to do or where to go next

I also dont have a "custom-pools.conf" file either.
If you want, we can set up a teamviewer session and you can take a look first hand..

**Comment by macboy80** [comment]
I'm having the same issue. No passwords/workers. Win7x64 and WinXPx32. .Zip is taking a while to download this time, so I think it's actually downloading. Web interface in latest Firefox.

http://pastebin.com/WPLWGJJc (I am rapidly clicking [+] to add a worker at the bottom of the paste)

**Comment by c00w** [comment]
@houseonfire The file is called worker.cfg and I added a blank one to the repo
@houseonfire A bunch of those errors are because I messed up something.

@macboy80 There was a bug in writing to the file it should be fixed now.

Everyone:
I found a couple bugs. So it sort of works. There is still a bug with it regenrating some backend data structures. Tracking it down now.

**Comment by c00w** [comment]
Everyone:

I redid a bunch of stuff so on first startup bitHopper instructs you on what is broken and you can always access /worker. Can you try with the latest code?

**Comment by macboy80** [comment]
Still the same on Win7x64... http://pastebin.com/EtyGndCf <---Logfile

Error:

Traceback (most recent call last):
  File "D:\BitHopper\Python27\lib\site-packages\gevent\greenlet.py", line 325, in run
    result = self._run(_self.args, *_self.kwargs)
  File "D:\BitHopper\bitHopper\scheduler.py", line 40, in bitHopper_server_update
    self.bitHopper.server_update()
  File "bitHopper.py", line 174, in server_update
    if self.scheduler.server_update():
  File "D:\BitHopper\bitHopper\scheduler.py", line 151, in server_update
    if not self.server_is_valid(current):
  File "D:\BitHopper\bitHopper\scheduler.py", line 76, in server_is_valid
    return info.is_valid() and info['role'] in self.valid_roles
AttributeError: 'NoneType' object has no attribute 'is_valid'
<Greenlet at 0x2d93080: <bound method DefaultScheduler.bitHopper_server_update of <scheduler.DefaultScheduler object at 0x02D94D90>>> failed with AttributeError

^C

**Comment by TimLinton** [comment]
I'm trying with the latest build and when I try to add new workers, the worker.cfg file isn't being populated

**Comment by c00w** [comment]
@macboy80 
You have no valid servers. Add some workers at localhost:8337/worker.

**Comment by c00w** [comment]
@houseonfire 
What version are you running and what platform.

**Comment by macboy80** [comment]
@c00w 
I assume you mean type workername and password and then click (+). I tried that several times during the above logfile with no success. There is no confirmation or feedback when I press (+) and worker.cfg is not modified.

**Comment by TimLinton** [comment]
I'm running the latest version of bithopper. I have windows 7 32bit. Python 2.7.

When I go to /worker, i type in the info and hit "+" and nothing happens. the workers.conf file isn't updating, nothing happens at all.

What is the syntax inside worker.conf? I'll just put the workers in the config files by hand.

Message me on messenger at houseonfire at live.com and we can set up a teamviewer thing if you want.

**Comment by c00w** [comment]
@macboy80 Thats not good. I'll investigate
@houseonfire The syntax is 
[pool name]
user1: pass1
user2: pass2

**Comment by Endeavour79** [comment]
Issue appears for me too. Fresh install. Win7 x64
Can't configure&save workers

**Comment by c00w** [comment]
Are any errors appearing?

**Comment by Endeavour79** [comment]
No error messages. Just nothing happens when I try to configure the workers via the web page.

**Comment by c00w** [comment]
So the plus button doesn't work? What browser are you using?

**Comment by Endeavour79** [comment]
I can press the plus button but nothing happens.
Using Firefox 10.
I can't use MSIE at all. It tries to download a file instead of rendering the website.

**Comment by c00w** [comment]
... Okay. So it only works in chrome. I found the bug!

**Comment by macboy80** [comment]
Firefox here also... Looks like stats don't load right either. I checked both my skin and default.

**Comment by simonk83** [comment]
Oh, I was just about to report this still broken.  I'll try Chrome I guess...

**Comment by c00w** [comment]
It works in chrome 20 and firefox 12 now that 0.3.2 is merged.
