### ISSUE TITLE
Priority not working for backup Pools

### ISSUE THREAD

**Issue by Nitrowolf** [c00w/bitHopper#643]
21:20:30|database: Cleaning Database
21:20:30|pool: pools-custom.cfg not found.
21:20:30|database: Cleaning Database
21:20:30|pool: Please configure some pools!
21:20:30|pool: Go to localhost:8337/worker
21:20:30|pool: Then restart bitHopper
21:20:31|lp: LP Module Load
21:20:31|plugin: Loading Config Files
Exception in thread Thread-60:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/home/XXX/bitHopper/Workers.py", line 56, in poll_thread
    self.workers_lock[item] = {}
AttributeError: Workers instance has no attribute 'workers_lock'

21:20:31|pool: pools-custom.cfg not found.
21:20:31|database: Cleaning Database
21:20:32|plugin: Plugin loading mode: manual
21:20:32|plugin: Loading Plugins
21:20:32|plugin: poolblocks has been disabled
21:20:32|plugin: lpworkbench has been disabled
21:20:32|plugin: lpbot has been disabled
21:20:32|plugin: blockaccuracy has been disabled
21:20:32|plugin: apiangel has been disabled
21:20:32|plugin: backdoor has been disabled
21:20:32|plugin: test has been disabled
21:20:32|plugin: lpdump has been disabled
21:20:32|plugin: payouts has been disabled
21:20:32|plugin: poclbm has been disabled
21:20:32|plugin: hookexample failed reading main config file: No option 'hookexample' in section: 'plugins'
21:20:32|plugin: hookexample has been disabled
21:20:32|plugin: rpcworklog loaded
21:20:32|bitHopper: Selecting scheduler: DefaultScheduler
21:20:32|bitHopper: Fatal Error, No valid pools configured!
21:20:32|api: bonuspool api error:'api_method'
21:20:32|api: gpumax api error:'api_method'
21:20:32|pool: Please configure some pools!
21:20:32|pool: Go to localhost:8337/worker
21:20:32|pool: Then restart bitHopper
21:20:32|work: Not in pool
21:20:32|work: Not in pool
21:20:32|work: Not in pool
21:20:32|api: eclipsemc:        7347427
21:20:32|pool: Please configure some pools!
21:20:32|pool: Go to localhost:8337/worker
21:20:32|pool: Then restart bitHopper
21:20:32|pool: Please configure some pools!
21:20:32|pool: Go to localhost:8337/worker
21:20:32|pool: Then restart bitHopper
21:20:32|api: slush:    1065941         1277.8gh/s      57min.
21:20:32|pool: Please configure some pools!
21:20:32|pool: Go to localhost:8337/worker
21:20:32|pool: Then restart bitHopper
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 390, in run
    result = self._run(_self.args, *_self.kwargs)
  File "/home/XXX/bitHopper/scheduler.py", line 40, in bitHopper_server_update
    self.bitHopper.server_update()
  File "bitHopper.py", line 174, in server_update
    if self.scheduler.server_update():
  File "/home/XXX/bitHopper/scheduler.py", line 151, in server_update
    if not self.server_is_valid(current):
  File "/home/XXX/bitHopper/scheduler.py", line 76, in server_is_valid
    return info.is_valid() and info['role'] in self.valid_roles
AttributeError: 'NoneType' object has no attribute 'is_valid'
<Greenlet at 0x9a2c8ec: <bound method DefaultScheduler.bitHopper_server_update of <scheduler.DefaultScheduler object at 0x9a4ab6c>>> failed with AttributeError

21:20:33|api: eclipsemc api error:'NoneType' object has no attribute 'is_valid'
21:20:33|api: slush api error:'NoneType' object has no attribute 'is_valid'
21:20:34|pool: Please configure some pools!
21:20:34|pool: Go to localhost:8337/worker
21:20:34|pool: Then restart bitHopper

Then trying to add a worker gives this and bithopper must be restarted:

21:22:37|website: Error in a wsgi function
21:22:37|website: Workers instance has no attribute 'workers_lock'
Traceback (most recent call last):
  File "/home/XXX/bitHopper/website.py", line 275, in handle_start
    return use_site.handle(env,start_response)
  File "/home/XXX/bitHopper/Workers.py", line 169, in handle
    self.handle_post(webob.Request(env))
  File "/home/XXX/bitHopper/Workers.py", line 184, in handle_post
    post['user'], post['pass'])
  File "/home/XXX/bitHopper/Workers.py", line 120, in add_worker
    if pool not in self.workers_lock:
AttributeError: Workers instance has no attribute 'workers_lock'
/worker

This is a bone stock git pull just now and it fails in numerous places.  Any ideas what might be going on?

**Comment by c00w** [comment]
I broke the code. Try it now it should be fixed.

**Comment by Nitrowolf** [comment]
That seems to have solved it.  However, got another issue now, two actually:
1. Clicking "info" from a "mined" pool no longer disables the mining on that pool... it will just keep happily mining that same pool.
2. This has been broken for awhile... at least on "backup" servers - priority does nothing.  You can set the priority to whatever you want and Bithopper will ignore the setting.  Is this intended for backup pools?  I have 3 backup pools that I want mined in order of priority, but it just selects the first one and will never switch unless it goes down, even if I have priority set to 1 and the other two set to 8 and 9.

**Comment by Nitrowolf** [comment]
Looking through the code, seems the problem is here:

```
    server_list = [server for server in server_list
                   if lambda x:self.pool.get_entry(x)['priority'] >= max_priority]
```

Should probably be moved below the 

 if len(server_list) == 0 and len(backup_list):

block of code

**Comment by c00w** [comment]
Thanks. Should be fixed now.

**Comment by c00w** [comment]
Also the mining on an info pool is already reported.

**Comment by Nitrowolf** [comment]
Just tested the priority thing.. didn't seem to solve the problem.  I haven't had a chance to go through the code further, though... but it's still mining on the first backup pool alphabetically.

**Comment by c00w** [comment]
Are you having it slice across the pools? Or just select the one with the lowest shares? That also effects it.

**Comment by Nitrowolf** [comment]
I haev it set to DefaultScheduler, and backup_type is reject rate... huh, maybe that is it.  There needs to be a reject threshold though, or just a "backup_type = priority" but with a reject threshold.  If my reject rate on a set of backup pools are all within a fraction of a percent of each other, I would like priority to apply... but of course if I'm getting 50% rejects from a pool, by all means hop away.

**Comment by c00w** [comment]
So its selecting by reject rate. Selecting one pool and then applying priority to it. I'll add a priority method.

**Comment by c00w** [comment]
Until I do that you can select the slice method and it will work.

**Comment by Nitrowolf** [comment]
Won't that just rotate through the backup pools equally?

**Comment by c00w** [comment]
It will produce a list of all valid backup pools. Which will then be sorted by priority. So it will do what you want with regards to priority sorting. The whole system is badly named and going to be thrown out soon.

**Comment by Nitrowolf** [comment]
Any luck with this?

**Comment by c00w** [comment]
It will be fixed in 0.3.2. Using the slice method will get you your expected behaviour.

**Comment by Nitrowolf** [comment]
Maybe I'm not understanding slice exactly then, it seems to be slicing between all of the backup pools when what I want is it to mine on Backup Pool A, unless it's down, then move to B, etc...

**Comment by c00w** [comment]
Give it slice + priority. It should work correctly.

**Comment by Nitrowolf** [comment]
It does not; it's still ignoring priority.  It just evenly slices through all the backup pools.

**Comment by c00w** [comment]
Uh oh. Thats not good.

**Comment by c00w** [comment]
Fixed in 0.3.2
