### ISSUE TITLE
payout no longer persistant in db

### ISSUE THREAD

**Issue by organofcorti** [c00w/bitHopper#77]
Since the update last night, any payout I enter does not survive a restart.

**Comment by c00w** [comment]
Huh. I see that also. I'll try and iron it down.

**Comment by c00w** [comment]
It should be fixed now.

**Comment by organofcorti** [comment]
just pulled the new vers then entered an amount on the webpage in the 'payout' section and waited for a 'writing to database' message before shutting bH down and restarting. 

It still zeroed it out after the webpage refreshed. Still not working - sorry!

**Comment by c00w** [comment]
It passes my test cases. Huh...

**Comment by c00w** [comment]
Well on my end I cannot spot an issue. I get the correct behavior. Which new version are you using?

**Comment by organofcorti** [comment]
I pulled about an hour ago. let me check.

**Comment by organofcorti** [comment]
I just git-pulled again and rechecked - my payout stats are still zeroing out on a restart. Run debug?

**Comment by organofcorti** [comment]
rm stats.db , payouts still not persistent.

**Comment by c00w** [comment]
Well this is bizarre. I'll deal with it later but I honestly have no clue why it works on my end and not on yours...

**Comment by organofcorti** [comment]
No worries. luckily I saw someone in the forums with the same problem or I'd
think I was going mad.
On Jul 31, 2011 8:33 PM, "c00w" <
reply@reply.github.com>
wrote:

**Comment by timonex** [comment]
I have this problem also. Running bithopper on Windows 7 x64. I've tried both command line and Idle GUI and DB payout stats fail to persist. Perhaps windows is opening the database as read only?

**Comment by c00w** [comment]
Not sure why it is happening. Its next on the list after LP and slice scheduler bug fixes.

**Comment by timonex** [comment]
I tried changing file permissions and taking ownership of stats.db to no effect. I then opened it in sqlite browser, entered the data there and saved. This DID work and the data now persists so there's at least a band aid in place.

**Comment by c00w** [comment]
I fixed it I think. Does it work now?

**Comment by c00w** [comment]
I think I fixed it. If it reappears reopen.

**Comment by organofcorti** [comment]
Was still having problems on most recent. Figured out what was going on. If put a payout on 0 shares I'd get 'Infinity' efficiency. After that the db would not longer have persistent payout stats. I deleted stats.db & entered payouts only for shares submitted, and it's all ok.

So I think the 'Infinity' efficiency is preventing the payout stats from being persistent.

**Comment by c00w** [comment]
Um.. The infinity is only on the web. Deleting you stats.db might have done something useful though.

**Comment by organofcorti** [comment]
I put a payout on a pool that I don't have shares in, the db lost persistence again and I had to delete stats.db again to regain persistence of payout stats. It's pretty consistent at my end. Anyway, it's fixed for me as long as I don't try to add a payout to a pool I don't yet have shares in.

**Comment by c00w** [comment]
are you running with the tip? And what platform are you on?

**Comment by organofcorti** [comment]
I use linuxcoin 0.21b via remotedesktop, and chromium as web browser.

Sorry, don't follow what you mean by the first question.

**Comment by c00w** [comment]
Sorry. Are you running the latest version of bitHopper?

**Comment by organofcorti** [comment]
I git cloned (instead of git pulling) about 18 hours ago.

git log gives the following as the most recent change:

user@linuxcoin:~/bitHopper$ git log
commit 4b29ab550c8aeda5b9e06990c17fb51260948fec
Author: clr ricec2@rpi.edu
Date:   Sat Aug 6 00:25:41 2011 -0500

**Comment by c00w** [comment]
Hmmm. I tested on my machine with no shares and I got persistent database payouts. I'll nuke my db and recheck.

**Comment by organofcorti** [comment]
I'll keep an eye on mine but it's working for the moment.

cheers!
